# --- Build (static site) ---
[build]
  publish = "/"

# --- Canonical domain: always use https://www.thewarpfoundary.ai ---
[[redirects]]
  from = "http://thewarpfoundary.ai/*"
  to   = "https://www.thewarpfoundary.ai/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "https://thewarpfoundary.ai/*"
  to   = "https://www.thewarpfoundary.ai/:splat"
  status = 301
  force  = true

# Keep your “thanks” pretty URL
[[redirects]]
  from = "/thanks"
  to   = "/thanks/"
  status = 301
  force  = true

# --- Security headers (fix mixed content + HSTS) ---
[[headers]]
  for = "/*"
    [headers.values]
    # Auto-upgrade any http:// resources to https:// (fixes the padlock)
    Content-Security-Policy = "upgrade-insecure-requests"
    # Enforce HTTPS going forward
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"