[build]
  publish = "/"

# --- Force HTTPS on correct domain ---
[[redirects]]
  from = "http://thewarpfoundary.ai/*"
  to   = "https://www.thewarpfoundary.ai/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "https://thewarpfoundary.ai/*"
  to   = "https://www.thewarpfoundary.ai/:splat"
  status = 301
  force  = true

# --- Thank-you URLs: support both pretty and .html ---
[[redirects]]
  from = "/thanks-compliance"
  to   = "/thanks-compliance.html"
  status = 301
  force  = true

[[redirects]]
  from = "/thanks-api"
  to   = "/thanks-api.html"
  status = 301
  force  = true

# --- Friendly aliases to real files (avoid 404s) ---
[[redirects]]
  from = "/apifusion"
  to   = "/api-fusion.html"
  status = 301
  force = true

[[redirects]]
  from = "/apifusion.html"
  to   = "/api-fusion.html"
  status = 301
  force = true

[[redirects]]
  from = "/api-fusion"
  to   = "/api-fusion.html"
  status = 301
  force = true

[[redirects]]
  from = "/compliance"
  to   = "/compliance.html"
  status = 301
  force = true