# --- Build (static site) ---
[build]
  publish = "/"

# --- Redirect root domain to www ---
[[redirects]]
  from = "https://thewarpfoundary.ai/*"
  to   = "https://www.thewarpfoundary.ai/:splat"
  status = 301
  force  = true

# --- Security headers (fix mixed content + HSTS) ---
[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"