[build]
  publish = "/"

# --- Force HTTPS on correct domain ---
[[redirects]]
  from = "http://thewarpfoundary.ai/*"
  to   = "https://www.thewarpfoundary.ai/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "https://thewarpfoundary.ai/*"
  to   = "https://www.thewarpfoundary.ai/:splat"
  status = 301
  force  = true